name: Deploy

permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main

jobs:
  deploy_stack:
    runs-on: ubuntu-latest # Changed to ubuntu-latest for broader runner availability, can be arm if needed
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn' # Using yarn as per original file

      - name: Install dependencies
        run: yarn install --frozen-lockfile # This will install ts-node, typescript, aws-cdk-lib etc.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
          aws-region: ${{ vars.AWS_TARGET_REGION }}
          role-session-name: "GithubActionsOSCChat"

      - name: Deploy Stack (via CDK)
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'OscChatStack'
          cdk_args: '--require-approval never'
          actions_comment: false
