name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
